const { v4: uuidv4 } = require("uuid");
const axios = require("axios").default;
const csv = require("fast-csv");
const fs = require("fs");
const argv = require("minimist")(process.argv.slice(2));
const constants = require("./constants.js");


function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

function equalsIgnoringCase(text, other) {
  return text.localeCompare(other, undefined, { sensitivity: 'accent' }) === 0;
}

/**
 * Authenticate this function must occur before any other API calls can be made
 * @param username
 * @param password
 * @returns {Promise<T>} A token is returned if the login is successful
 */
async function login(username, password) {
  username = "danyfu@bu.edu";
  password = "foobar";

  return axios
    .post(constants.ENDPOINTS.LOGIN, {
      username: username,
      password: password,
    })
    .then((res) => {
      console.log(`Authentication status code: ${res.status}`);
      if(res.status === 200){
        axios.defaults.headers.common['Authorization'] = res.data.token;
      }
      return res.status;
    })
    .catch((error) => {
      console.error(error);
      return null;
    });
}

async function makeSample(name){
  if(!name){
    name = uuidv4();
  }
    return axios
      .post(constants.ENDPOINTS.CREATE_SAMPLE, {
        sampleTypeID: 33369,
        name: name,
      })
      .then((res) => {
        console.log(`Make sample statusCode: ${res.status}`);
        if (res.status === 200){
          console.log(`New sample ID: ${res.data}`);
          return res.data;
        }
      })
      .catch((error) => {
        console.error(error);
      });
}

/**
 * Update a custom field for a sample
 * @param sampleId The unique ID of the sample generated by eLabs
 * @param key Name of the field to be updated
 * @param value Value of the field to be updated
 * @param type The field type (dropdown, text, radio button, etc)
 * @returns {Promise<void>}
 */
async function updateMeta({sampleId, key, value, type}={}){
  return axios
    .put(`https://us.elabjournal.com/api/v1/samples/${sampleId}/meta`, {
      key: key,
      value: value,
      sampleDataType: type,
    })
    .then((res) => {
      console.log(`Update sample: ${sampleId}, field:${key}, statusCode: ${res.status}`);
      console.log(res.data);
    })
    .catch((error) => {
      console.error(error);
    });
}

async function makeBatchSamples(){

  await login();

  let plateRows = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];
  let plateCols = Array.from(Array(12), (_, i) => i + 1);
  let plate_coordinates_96 = [];
  for (let i = 0; i < plateRows.length; i++) {
    for (let j = 0; j < plateCols.length; j++) {
      plate_coordinates_96.push(`${plateRows[i]}${plateCols[j]}`);
    }
  }

  for (let i = 0; i < plate_coordinates_96.length; i++) {
    let sampleId = await makeSample();
    if (sampleId){
      updateMeta(sampleId, constants.META.SAMPLE_BC.KEY,
                 `sample-barcode-plate11-${plate_coordinates_96[i]}`,
                  constants.META.SAMPLE_BC.TYPE);
    } else {
      console.log("No Sample ID")
    }
  }
}

/**
 * Return all Patient Samples and their meta fields that matches a search term
 * @param searchTerm
 * @returns {Promise<void>}
 */
async function searchForPatienSample(searchTerm){
  await login();

  return axios.get(`${constants.ENDPOINTS.GET_ALL_PATIENT_SAMPLES}&search=${searchTerm}`)
    .then((res) => {
      console.log(`statusCode: ${res.status}`);
      return res.data;
    })
    .catch((error) => {
      console.error(error);
    });
}

/**
 * Find a Patient Sample with the given barcode (which is also its name)
 * @param barcode
 * @returns {Promise<void>} Sample object if found, else Null
 */
async function getPatientSample(barcode){
  return axios.get(`${constants.ENDPOINTS.GET_PATIENT_SAMPLE}&name=${barcode}`)
    .then((res) => {
      console.log(`statusCode: ${res.status}`);
      if(res.status === 200 && res.data.data.length > 0){
        return res.data.data[0].sampleID;
      }
      return null;
    })
    .catch((error) => {
      console.error(error);
      return null;
    });
}

/**
 * Update PatientSample with the plate barcode and well number
 * from the Sample Prep Hamilton and update status
 * @param sampleID
 * @param destBC
 * @param destWellNum
 * @returns {Promise<void>}
 */
async function samplePrepTracking(sampleID, destBC, destWellNum){
  console.log("sample prep");
  updateMeta({sampleId:sampleID,
    key: constants.META.DEEPWELL_BC.KEY,
    value: destBC,
    type: constants.META.DEEPWELL_BC.TYPE}); //update RNA Plate Barcode
  updateMeta({sampleId:sampleID,
    key: constants.META.DEEPWELL_WELL_NUM.KEY,
    value: destWellNum,
    type: constants.META.DEEPWELL_WELL_NUM.TYPE}); //update RNA Plate Well Location
  updateMeta({sampleId:sampleID,
    key: constants.META.STATUS.KEY,
    value: constants.STATUS_VAL.SAMPLE_PREP_DONE,
    type: constants.META.STATUS.TYPE}); //update status to "Sample Transferred To 96-Well Plate"
}

/**
 * Updates PatientSample with the plate barcode and well number
 * from the RNA Extraction Hamilton and update status
 * @param sampleID
 * @param destBC
 * @param destWellNum
 * @returns {Promise<void>}
 */
async function rnaExtractionTracking(sampleID, destBC, destWellNum){
  console.log("RNA extraction");
  updateMeta({sampleId:sampleID,
    key: constants.META.RNA_PLATE_BC.KEY,
    value: destBC,
    type: constants.META.RNA_PLATE_BC.TYPE}); //update RNA Plate Barcode
  updateMeta({sampleId:sampleID,
    key: constants.META.RNA_PLATE_WELL_NUM.KEY,
    value: destWellNum,
    type: constants.META.RNA_PLATE_WELL_NUM.TYPE}); //update RNA Plate Well Location
  updateMeta({sampleId:sampleID,
    key: constants.META.STATUS.KEY,
    value: constants.STATUS_VAL.RNA_DONE,
    type: constants.META.STATUS.TYPE}); //update status to "RNA Extracted"
}

/**
 * Updates PatientSample with the plate barcode and well number
 * from the qPCR Prep Hamilton and update status
 * @param sampleID
 * @param destBC
 * @param destWellNum
 * @returns {Promise<void>}
 */
function qPCRPrepTracking(sampleID, destBC, destWellNum){
  console.log("qPCR prep");
  updateMeta({sampleId:sampleID,
              key: constants.META.QPCR_PLATE_BC.KEY,
              value: destBC,
              type: constants.META.QPCR_PLATE_BC.TYPE}); //update qPCR Plate Barcode
  updateMeta({sampleId:sampleID,
              key: constants.META.QPCR_PLATE_WELL_NUM.KEY,
              value: destWellNum,
              type: constants.META.QPCR_PLATE_WELL_NUM.TYPE}); //update qPCR Plate Well Location
  updateMeta({sampleId:sampleID,
              key: constants.META.STATUS.KEY,
              value: constants.STATUS_VAL.QPCR_PREP_DONE,
              type: constants.META.STATUS.TYPE}); //update status to "qPCR Reactions Prepared"
}

/**
 * Updates PatientSample with CT values and final result
 * from the QuantStudio and update status
 * @param sampleID
 * @param ctN1
 * @param ctN2
 * @param ctRP
 * @param result
 * @returns {Promise<void>}
 */
async function qPCRRunTracking(sampleID, ctN1, ctN2, ctRP, result){
  console.log("qPCR Run");
  updateMeta({sampleId:sampleID,
    key: constants.META.CT_N1.KEY,
    value: ctN1,
    type: constants.META.CT_N1.TYPE}); //update N1 CT value
  updateMeta({sampleId:sampleID,
    key: constants.META.CT_N2.KEY,
    value: ctN2,
    type: constants.META.CT_N2.TYPE}); //update N2 CT value
  updateMeta({sampleId:sampleID,
    key: constants.META.CT_RP.KEY,
    value: ctRP,
    type: constants.META.CT_RP.TYPE}); //update Rnase P CT value
  updateMeta({sampleId:sampleID,
    key: constants.META.RESULT.KEY,
    value: result,
    type: constants.META.RESULT.TYPE}); //update COVID-19 Test Result
  updateMeta({sampleId:sampleID,
    key: constants.META.STATUS.KEY,
    value: constants.STATUS_VAL.QPCR_DONE,
    type: constants.META.STATUS.TYPE}); //update status to "qPCR Run"
}

/**
 * Calls the appropriate update function based on protocol
 * @param csvRow row in the CSV
 */
async function lineageTracking(csvRow){
  let protocol = csvRow[constants.PROTOCOL].toUpperCase();
  if (!protocol || (!(protocol in constants.ORIGIN_VAL))){
    console.log(`${protocol} is not recognized as a supported process. Must be one of the four values: 
              ${Object.keys(constants.ORIGIN_VAL)}. Index ${csvRow[constants.PROTOCOL]} not processed.`);
    return;
  }

  let sampleBC = csvRow["Sample Tube Barcode"];
  let sampleID = await getPatientSample(sampleBC);
  if(!sampleID){
    console.log(`Sample for barcode ID ${sampleBC} not found`);
    return;
  }

  if(equalsIgnoringCase(protocol, constants.ORIGIN_VAL.QPCR_RUN)){
    let ctN1;
    let ctN2;
    let ctRP;
    let result;
    qPCRRunTracking(sampleID, ctN1, ctN2, ctRP, result);

  } else {

    let destBC = csvRow["Output Barcode"];
    let destWellNum = csvRow["Output Well Number"];

    switch(protocol){
      case constants.ORIGIN_VAL.SAMPLE_PREP:
        samplePrepTracking(sampleID, destBC, destWellNum);
        break;
      case constants.ORIGIN_VAL.RNA_EXTRACTION:
        rnaExtractionTracking(sampleID, destBC, destWellNum);
        break;
      case constants.ORIGIN_VAL.QPCR_PREP:
        qPCRPrepTracking(sampleID, destBC, destWellNum);
        break;
    }
  }
}

async function parse_logfile(logfile){
  // console.log(logfile);
  // console.log(origin);
  console.log(`Log begin: ${new Date().toLocaleString("en-US", {timeZone: "America/New_York"})}\n`);

  let auth = await login();
  if (!auth || auth !== 200){
    console.log(`Failed to log into eLabs.`);
    return;
  }

  fs.createReadStream(logfile)
    .pipe(csv.parse({ headers: true }))
    .on('error', error => console.error(error))
    .on('data', (row) => {
      lineageTracking(row);
    })
    .on('end', (rowCount) => console.log(`Parsed ${rowCount} records`));
}

/**
 * file: path of the CSV file to be parsed
 */
parse_logfile(argv.file);


